# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1659447ab0fa04c4b6bb5527856aca8ecb2e24d2aedd58f8b3221631871d863b818ff316fcd1b92dbde8bfeeb3a365e6697b202661ad428ea5d3a3f7bfc62a8

test:
  secret_key_base: 01e4f7e4a4e81f0fa7295cc6b733c87a07a76cb511389d600eb5be6d07febc7053bb865298b5751f927bf181f71d4e35e27f20427c81dfae685a695b05350916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
