# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc60d3363c049f3afb72aee9562cbd7b702a775cf1f0d6793a974a407e7d02a91f2a63135e0312e436f0d4519eec297e7c360f962c0826c25ac9c6658c5a3719

test:
  secret_key_base: e774ae6b62b6983d528b8dc45aa1137d2197a57a357fc980e352c41fa985005c516d470b992fc7d46151ee2dbc78a784c21381b8c2e3a9e9dceae0ef8b04e60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
